PACKAGE_NAME="akb_pcr20x"
PACKAGE_VERSION="0.0.1"

MAKE[0]="make KDIR=/lib/modules/$kernelver/build"
CLEAN="make clean"

BUILT_MODULE_NAME[0]="akb_pcr20x"
BUILT_MODULE_LOCATION[0]="src/"
DEST_MODULE_LOCATION[0]="/updates/dkms"

BUILT_MODULE_NAME[1]="stv6110a"
BUILT_MODULE_LOCATION[1]="src/"
DEST_MODULE_LOCATION[1]="/updates/dkms"

BUILT_MODULE_NAME[2]="mxl135rf"
BUILT_MODULE_LOCATION[2]="src/"
DEST_MODULE_LOCATION[2]="/updates/dkms"

AUTOINSTALL="yes"